### GET -> EVENT BY ID
GET http://localhost:8080/events/1 HTTP/1.1

### GET -> ALL EVENTS
GET http://localhost:8080/events HTTP/1.1

### POST -> CREATE EVENT
POST http://localhost:8080/events/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY0MTIxNjI4MywiZXhwIjoxNjQxMjE3NDgzfQ.-_IVd4PpXZPo3HXSxjs1SkCFbof7eiU2GUBanNJ1o1w

{
  "name": "Event name 2",
  "place": "Some location",
  "date": "12-10-2021"
}

### PUT -> EDIT EVENT WITH ID
PUT http://localhost:8080/events/1/edit
Content-Type: application/json

{
  "name": "Event name",
  "place": "Some location",
  "date": "2021-09-05"
}

### PUT -> ADD TEAM WITH TEAMID TO EVENT WITH EVENTID 
PUT http://localhost:8080/events/2/addTeam
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY0MTIxNjI4MywiZXhwIjoxNjQxMjE3NDgzfQ.-_IVd4PpXZPo3HXSxjs1SkCFbof7eiU2GUBanNJ1o1w

{
  "TeamId": 1
}

### PUT -> REMOVE TEAM WITH TEAMID FROM EVENT WITH EVENTID 
PUT http://localhost:8080/events/1/removeTeam
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY0MTIxNTQ0OSwiZXhwIjoxNjQxMjE2NjQ5fQ.zg7lFkF77-O73HEE-pjw99jd4Exe4D8JB2jGG3-QSik

{
  "TeamId": 1
}

### DELETE -> EVENT BY ID
DELETE http://localhost:8080/events/1/delete HTTP/1.1