### GET -> TASK BY ID
GET http://localhost:8080/tasks/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY0MTIxODA0NiwiZXhwIjoxNjQxMjE5MjQ2fQ.zU1gUh6U9cUlxAQAgs4VArlhUcTk1E6V162XH7tLSCg

### GET -> ALL TASKS
GET http://localhost:8080/tasks HTTP/1.1

### POST -> CREATE TASK
POST http://localhost:8080/tasks/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY0MTIxNjI4MywiZXhwIjoxNjQxMjE3NDgzfQ.-_IVd4PpXZPo3HXSxjs1SkCFbof7eiU2GUBanNJ1o1w

{
  "name": "Task 1",
  "date": "2021-09-10",
  "priority": "low",
  "EventId": 1,
  "TeamId": 1
}

### PUT -> ADD USER WITH USERID TO TASK WITH TASKID 
PUT http://localhost:8080/tasks/1/addUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY0MTIxODA0NiwiZXhwIjoxNjQxMjE5MjQ2fQ.zU1gUh6U9cUlxAQAgs4VArlhUcTk1E6V162XH7tLSCg

{
  "UserId": 1
}

### PUT -> REMOVE USER WITH USERID TO TASK WITH TASKID 
PUT http://localhost:8080/tasks/1/removeUser
Content-Type: application/json

{
  "UserId": 1
}


### PUT -> EDIT TASK WITH ID
PUT http://localhost:8080/tasks/1/edit
Content-Type: application/json

{
  "TeamId": 0
}

### DELETE -> TASK BY ID
DELETE http://localhost:3000/tasks/1/delete HTTP/1.1