### GET -> USER BY ID
GET http://localhost:8080/users/1 HTTP/1.1

### GET -> ALL USERS
GET http://localhost:8080/users HTTP/1.1


### POST -> LOGIN USER
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "testpassword"
}

### POST -> CREATE user
POST http://localhost:8080/users/create HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "user1@test.com",
  "phoneNumber": "+48000000002",
  "password": "password",
  "rolex": "User"
}

### PUT -> EDIT USER WITH ID
PUT http://localhost:8080/users/1/edit
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "admin@test.com",
  "phoneNumber": "+48000000001",
  "password": "password",
  "role": "Admin"
}

### DELETE -> USER BY ID
DELETE http://localhost:8080/users/2/delete HTTP/1.1

### GET -> OVERDUE TASKS OF USER WITH ID
GET http://localhost:8080/users/1/overdueTasks HTTP/1.1

### GET -> OVERDUE TASKS OF USER WITH ID
GET http://localhost:8080/users/1/getEvents HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY0MTIxODA0NiwiZXhwIjoxNjQxMjE5MjQ2fQ.zU1gUh6U9cUlxAQAgs4VArlhUcTk1E6V162XH7tLSCg